### ISSUE TITLE
Unable to run on Linux

### ISSUE THREAD

**Issue by Manouchehri** [hallewhittaker/hallewhittaker#2]
```
Traceback (most recent call last):
  File "./git2csv.py", line 62, in <module>
    z= subprocess.run('git ls-tree --full-tree --name-only -r HEAD', stdout= subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git ls-tree --full-tree --name-only -r HEAD': 'git ls-tree --full-tree --name-only -r HEAD'
```

Steps to reproduce on Linux:

```sh
git clone https://github.com/hallewhittaker/git2csv.git
cd git2csv
./git2csv.py . test.json
```

I definitely do have git installed though! =) 

```
dave@xps:~$ git --version
git version 2.17.1
```

**Comment by Manouchehri** [comment]
Fixed in 91f48bdc3648ff96acbed4fcf1508f93e279b8c2, thanks!
